language: generic
sudo: required

before_install:
  - export
  - chmod +x .travis/*.sh
  - sudo add-apt-repository ppa:ansible/ansible-2.6
  - sudo apt-get update
  - sudo apt-get install -y ansible
install: true
jobs:
  include:
    - stage: deployment
      script:
        - "./.travis/cron-dev.sh"