---
docker_secrets:
    - name: "DO_AUTH_TOKEN"
      value: !vault |
               $ANSIBLE_VAULT;1.1;AES256
               38666639643937313237623730616532656432313734313662333033396663353937623263373337
               3861383362356335623563383066643766663261646232330a306138356365343761616435306661
               39643939323533643334616565303232346362666662393235623234313466373634353136626337
               3861643237623763330a393131333664643934623637316637663065633563636537356239366333
               62336638366564326337326465616332643730383263343262313133346436383532386537343530
               37383865613563303130616431633631633633373731613037373865343238366434633866303062
               38376262333861333364376563623834333234346131333362353638663562303763376534613435
               34373264373438336661
    - name: "MONGO_INITDB_ROOT_USERNAME"
      value: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              65313731333664326664376137356239313836363235383836316538613930623435383366326337
              3933656139346266393064613731333863343362316539660a383536663236643338613532343630
              61346137353634613631326366353133663539313933356665363134383537366462386363326636
              6537653665323832300a336131633230613864653835326536306134333062316462613533326637
              6334
    - name: "MONGO_INITDB_ROOT_PASSWORD"
      value: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              30323036333837333564396466363566303266663465383261396133626633363634613864336465
              3239373364313735363363643563313937666462653437300a373232346133643661363137656537
              32396630396165316238323335663832343238366333326433383838653365616238616461623230
              3339643833316630660a653231663066343966383434353063303631383065666465646465346234
              6230
    - name: "DEV_TOKEN_KEY_SECRET"
      value: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              35343661346436353634306337656134303264623966393732643763373361316461373862356537
              3439633534333666636532656365346161373536363430660a616363366464666162343334376638
              62363335343132666632336164626131643232646537326339376439343762393137383261303138
              3063653865326564620a333733303361653231373633393631613631616135636231396330616436
              38633737643565333237303137323635316132376462373834363134346138326263