---
docker_secrets:
  - name: "DO_AUTH_TOKEN"
    value: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            36633533376535373063313764393138353332353936326138303961613639633862363862313536
            3363623732663161346431396334613331373834376464640a613639336364333666373539343831
            39363966643233373230633836326638313864333864366466306465326638326436383962313663
            6134343737373736640a646366646161363838303637336237623037663438663730346137613935
            38666137353836316238393735626264646438646137303532383261343139656333366564633766
            36323433613862376166383764373230626432303431346465333039353264653266653338616231
            35616535383533616364376530316438353437646539383962303930616537323364366531366434
            32633438393837343335